using TubeForge.Core.Media;
using TubeForge.Tests.Framework;
using TubeForge.YouTube.Extraction;

namespace TubeForge.Tests.YouTube;

public static class YouTubeWatchPageParserTests
{
    [Test]
    public static void MapsMetadataFormatsAndPlayerScript()
    {
        var html = File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Fixtures", "watch-page-basic.html"));
        var result = YouTubeWatchPageParser.Parse(html);

        Assert.True(result.IsSuccess, result.Error?.TechnicalDetail);
        Assert.Equal("Fixture123_", result.Value.Metadata.Id.Value);
        Assert.Equal("Fixture {video}; title", result.Value.Metadata.Title);
        Assert.Equal("Fixture channel", result.Value.Metadata.Channel);
        Assert.Equal(TimeSpan.FromSeconds(123), result.Value.Metadata.Duration);
        Assert.Equal(
            "https://i.ytimg.com/vi/Fixture123_/hqdefault.jpg",
            result.Value.Metadata.ThumbnailUrl?.AbsoluteUri);
        Assert.Equal(2, result.Value.Metadata.Formats.Count);
        Assert.Equal(2, result.Value.Metadata.CaptionTracks.Count);
        Assert.Equal(2, result.Value.Metadata.Chapters.Count);
        Assert.Equal("Introduction", result.Value.Metadata.Chapters[0].Title);
        Assert.Equal(TimeSpan.Zero, result.Value.Metadata.Chapters[0].StartTime);
        Assert.Equal("Main section", result.Value.Metadata.Chapters[1].Title);
        Assert.Equal(TimeSpan.FromMinutes(1), result.Value.Metadata.Chapters[1].StartTime);
        Assert.Equal(1, result.Value.CipheredFormatCount);
        Assert.Equal(
            "https://www.youtube.com/s/player/fixture/player_ias.vflset/en_US/base.js",
            result.Value.PlayerScriptUrl?.AbsoluteUri);

        var progressive = result.Value.Metadata.Formats.Single(format => format.FormatId == 22);
        Assert.Equal(StreamKind.Progressive, progressive.Kind);
        Assert.Equal(VideoCodec.H264, progressive.VideoCodec);
        Assert.Equal(AudioCodec.Aac, progressive.AudioCodec);
        Assert.Equal(1280, progressive.Width);
        Assert.Equal(720, progressive.Height);
        Assert.Equal(134_217_728L, progressive.ContentLength);

        var audio = result.Value.Metadata.Formats.Single(format => format.FormatId == 251);
        Assert.Equal(StreamKind.AudioOnly, audio.Kind);
        Assert.Equal(MediaContainer.WebM, audio.Container);
        Assert.Equal(AudioCodec.Opus, audio.AudioCodec);
        Assert.Equal(48_000, audio.AudioSampleRate);

        var englishCaption = result.Value.Metadata.CaptionTracks.Single(track => track.LanguageCode == "en");
        Assert.Equal("English", englishCaption.Name);
        Assert.Equal(".en", englishCaption.VssId);
        Assert.False(englishCaption.IsAutoGenerated);
        Assert.True(englishCaption.IsTranslatable);
        Assert.Equal("https://www.youtube.com/api/timedtext?v=Fixture123_&lang=en", englishCaption.Url.AbsoluteUri);

        var germanCaption = result.Value.Metadata.CaptionTracks.Single(track => track.LanguageCode == "de");
        Assert.Equal("German (auto-generated)", germanCaption.Name);
        Assert.True(germanCaption.IsAutoGenerated);
        Assert.False(germanCaption.IsTranslatable);
    }

    [Test]
    public static void PrefersLargestWidescreenThumbnailOverLetterboxedFourByThreeVariant()
    {
        var result = YouTubeWatchPageParser.Parse(PlayerResponse("""
            "videoDetails":{
              "videoId":"Fixture123_","title":"Thumbnail fixture",
              "thumbnail":{"thumbnails":[
                {"url":"https://i.ytimg.com/vi/Fixture123_/default.jpg","width":120,"height":90},
                {"url":"https://i.ytimg.com/vi/Fixture123_/mqdefault.jpg","width":320,"height":180},
                {"url":"https://i.ytimg.com/vi/Fixture123_/maxresdefault.jpg","width":1280,"height":720},
                {"url":"https://i.ytimg.com/vi/Fixture123_/hqdefault.jpg","width":480,"height":360}
              ]}
            }
            """));

        Assert.True(result.IsSuccess, result.Error?.TechnicalDetail);
        Assert.Equal(
            "https://i.ytimg.com/vi/Fixture123_/maxresdefault.jpg",
            result.Value.Metadata.ThumbnailUrl?.AbsoluteUri);
    }

    [Test]
    public static void MapsDescriptionChaptersFromInitialDataWhenPlayerResponseOmitsThem()
    {
        var html = PlayerResponse("""
            "videoDetails":{
              "videoId":"Fixture123_","title":"Initial data chapters","lengthSeconds":"123"
            }
            """) + """
            <script>var ytInitialData={
              "playerOverlays":{"playerOverlayRenderer":{"decoratedPlayerBarRenderer":{"decoratedPlayerBarRenderer":{
                "playerBar":{"multiMarkersPlayerBarRenderer":{"markersMap":[{
                  "key":"DESCRIPTION_CHAPTERS",
                  "value":{"chapters":[
                    {"chapterRenderer":{"title":{"simpleText":"Introduction"},"timeRangeStartMillis":0}},
                    {"chapterRenderer":{"title":{"runs":[{"text":"Main "},{"text":"section"}]},"timeRangeStartMillis":60000}}
                  ]}
                }]}}
              }}}}
            };</script>
            """;

        var result = YouTubeWatchPageParser.Parse(html);

        Assert.True(result.IsSuccess, result.Error?.TechnicalDetail);
        Assert.Equal(2, result.Value.Metadata.Chapters.Count);
        Assert.Equal("Introduction", result.Value.Metadata.Chapters[0].Title);
        Assert.Equal(TimeSpan.Zero, result.Value.Metadata.Chapters[0].StartTime);
        Assert.Equal("Main section", result.Value.Metadata.Chapters[1].Title);
        Assert.Equal(TimeSpan.FromMinutes(1), result.Value.Metadata.Chapters[1].StartTime);
    }

    [Test]
    public static void RejectsEmptyMalformedAndUnavailableResponses()
    {
        Assert.False(YouTubeWatchPageParser.Parse(null).IsSuccess);
        Assert.False(YouTubeWatchPageParser.Parse("<html>none</html>").IsSuccess);
        Assert.False(YouTubeWatchPageParser.Parse(
            "<script>var ytInitialPlayerResponse={broken};</script>").IsSuccess);

        var unavailable = YouTubeWatchPageParser.Parse(
            "<script>var ytInitialPlayerResponse={\"playabilityStatus\":{\"status\":\"ERROR\",\"reason\":\"Gone\"}," +
            "\"videoDetails\":{\"videoId\":\"Fixture123_\",\"title\":\"Fixture\"}};</script>");
        Assert.False(unavailable.IsSuccess);
        Assert.Equal("Video.Unavailable", unavailable.Error?.Code);

        var loginRequired = YouTubeWatchPageParser.Parse(
            "<script>var ytInitialPlayerResponse={\"playabilityStatus\":{\"status\":\"LOGIN_REQUIRED\",\"reason\":\"Private fixture detail\"}," +
            "\"videoDetails\":{\"videoId\":\"Fixture123_\",\"title\":\"Fixture\"}};</script>");
        Assert.False(loginRequired.IsSuccess);
        Assert.Equal("Video.AuthenticationUnsupported", loginRequired.Error?.Code);
        Assert.Equal(
            "Authenticated and access-controlled media are intentionally unsupported in TubeForge v2.",
            loginRequired.Error?.Message);
        Assert.False(loginRequired.Error!.Message.Contains("fixture", StringComparison.OrdinalIgnoreCase));

        var hostileThumbnail = YouTubeWatchPageParser.Parse(
            "<script>var ytInitialPlayerResponse={\"playabilityStatus\":{\"status\":\"OK\"}," +
            "\"videoDetails\":{\"videoId\":\"Fixture123_\",\"title\":\"Fixture\"," +
            "\"thumbnail\":{\"thumbnails\":[{\"url\":\"https://evil.invalid/thumbnail.jpg\"}]}}};</script>");
        Assert.True(hostileThumbnail.IsSuccess, hostileThumbnail.Error?.TechnicalDetail);
        Assert.Equal<Uri?>(null, hostileThumbnail.Value.Metadata.ThumbnailUrl);
    }

    [Test]
    public static void ClassifiesShortsAndCompletedLiveReplays()
    {
        var shortResult = YouTubeWatchPageParser.Parse(PlayerResponse("""
            "videoDetails":{
              "videoId":"Fixture123_","title":"Short fixture","lengthSeconds":"15",
              "isShortsEligible":true
            }
            """));
        var replayResult = YouTubeWatchPageParser.Parse(PlayerResponse("""
            "videoDetails":{
              "videoId":"Fixture123_","title":"Replay fixture","lengthSeconds":"3600",
              "isLiveContent":true,"isLive":false
            },
            "microformat":{"playerMicroformatRenderer":{"liveBroadcastDetails":{
              "startTimestamp":"2026-07-15T18:00:00Z",
              "endTimestamp":"2026-07-15T19:00:00Z",
              "isLiveNow":false
            }}}
            """));

        Assert.True(shortResult.IsSuccess, shortResult.Error?.TechnicalDetail);
        Assert.Equal(VideoContentKind.Short, shortResult.Value.Metadata.ContentKind);
        Assert.True(replayResult.IsSuccess, replayResult.Error?.TechnicalDetail);
        Assert.Equal(VideoContentKind.LiveReplay, replayResult.Value.Metadata.ContentKind);
        Assert.Equal(
            new DateTimeOffset(2026, 7, 15, 18, 0, 0, TimeSpan.Zero),
            replayResult.Value.Metadata.LiveStartedAtUtc);
        Assert.Equal(
            new DateTimeOffset(2026, 7, 15, 19, 0, 0, TimeSpan.Zero),
            replayResult.Value.Metadata.LiveEndedAtUtc);
    }

    [Test]
    public static void MapsActiveAndUpcomingLiveCaptureModes()
    {
        var active = YouTubeWatchPageParser.Parse(PlayerResponse("""
            "videoDetails":{
              "videoId":"Fixture123_","title":"Active fixture","isLiveContent":true,"isLive":true
            },
            "streamingData":{"hlsManifestUrl":"https://manifest.googlevideo.com/api/manifest/hls_playlist/test.m3u8"}
            """));
        var activeWithoutWatchManifest = YouTubeWatchPageParser.Parse(PlayerResponse("""
            "videoDetails":{
              "videoId":"Fixture123_","title":"Active fallback fixture","isLiveContent":true,"isLive":true
            }
            """));
        var upcoming = YouTubeWatchPageParser.Parse("""
            <script>var ytInitialPlayerResponse={
              "playabilityStatus":{"status":"LIVE_STREAM_OFFLINE","reason":"Starts later"},
              "videoDetails":{"videoId":"Fixture123_","title":"Upcoming fixture","isLiveContent":true},
              "microformat":{"playerMicroformatRenderer":{"liveBroadcastDetails":{
                "startTimestamp":"2099-07-16T20:00:00Z","isLiveNow":false
              }}}
            };</script>
            """);

        Assert.True(active.IsSuccess, active.Error?.Message);
        Assert.Equal(VideoContentKind.LiveActive, active.Value.Metadata.ContentKind);
        Assert.True(active.Value.Metadata.Formats.Single().IsLiveHls);
        Assert.False(active.Value.Metadata.Formats.Single().IsLiveManifestPending);
        Assert.Equal(YouTubeWatchPageParser.LiveHlsFormatId, active.Value.Metadata.Formats.Single().FormatId);

        Assert.True(activeWithoutWatchManifest.IsSuccess, activeWithoutWatchManifest.Error?.Message);
        Assert.Equal(VideoContentKind.LiveActive, activeWithoutWatchManifest.Value.Metadata.ContentKind);
        Assert.True(activeWithoutWatchManifest.Value.Metadata.Formats.Single().IsLiveManifestPending);
        Assert.Equal("LiveManifestClientFallback", activeWithoutWatchManifest.Value.Diagnostics?.Stage);

        Assert.True(upcoming.IsSuccess, upcoming.Error?.Message);
        Assert.Equal(VideoContentKind.LiveUpcoming, upcoming.Value.Metadata.ContentKind);
        Assert.True(upcoming.Value.Metadata.Formats.Single().IsLiveManifestPending);
    }

    [Test]
    public static void KeepsOriginalAudioOverLoudnessCompressedDuplicate()
    {
        var result = YouTubeWatchPageParser.Parse(PlayerResponse("""
            "videoDetails":{"videoId":"Fixture123_","title":"DRC fixture","lengthSeconds":"10"},
            "streamingData":{"adaptiveFormats":[{
              "itag":251,
              "url":"https://fixture.googlevideo.com/videoplayback?id=original&itag=251",
              "mimeType":"audio/webm; codecs=\"opus\"",
              "bitrate":143452,"audioSampleRate":"48000","audioChannels":2,"contentLength":"20"
            },{
              "itag":251,
              "url":"https://fixture.googlevideo.com/videoplayback?id=drc&itag=251",
              "mimeType":"audio/webm; codecs=\"opus\"",
              "bitrate":143908,"audioSampleRate":"48000","audioChannels":2,"isDrc":true,
              "contentLength":"20"
            }]}
            """));

        Assert.True(result.IsSuccess, result.Error?.Message);
        var audio = result.Value.Metadata.Formats.Single();
        // The compressed duplicate declares the higher bitrate, so a bitrate-only comparison
        // would silently downgrade every download to the loudness-normalised track.
        Assert.False(audio.IsDrc);
        Assert.Equal(143452L, audio.Bitrate);
        Assert.Equal(2, audio.AudioChannels);
        Assert.True(audio.Url.Query.Contains("id=original", StringComparison.Ordinal));
    }

    [Test]
    public static void KeepsOriginalLanguageAudioOverDubbedTrackWithSameFormatId()
    {
        var result = YouTubeWatchPageParser.Parse(PlayerResponse("""
            "videoDetails":{"videoId":"Fixture123_","title":"Dub fixture","lengthSeconds":"10"},
            "streamingData":{"adaptiveFormats":[{
              "itag":140,
              "url":"https://fixture.googlevideo.com/videoplayback?id=dubbed&itag=140",
              "mimeType":"audio/mp4; codecs=\"mp4a.40.2\"",
              "bitrate":130000,"contentLength":"20",
              "audioTrack":{"id":"de.3","displayName":"German","audioIsDefault":false}
            },{
              "itag":140,
              "url":"https://fixture.googlevideo.com/videoplayback?id=original&itag=140",
              "mimeType":"audio/mp4; codecs=\"mp4a.40.2\"",
              "bitrate":130000,"contentLength":"20",
              "audioTrack":{"id":"en.4","displayName":"English original","audioIsDefault":true}
            }]}
            """));

        Assert.True(result.IsSuccess, result.Error?.Message);
        var audio = result.Value.Metadata.Formats.Single();
        Assert.True(audio.IsOriginalAudio);
        Assert.Equal("en", audio.AudioLanguage);
        Assert.True(audio.Url.Query.Contains("id=original", StringComparison.Ordinal));
    }

    [Test]
    public static void MarksWideColourGamutLadderEntriesAsHdr()
    {
        var result = YouTubeWatchPageParser.Parse(PlayerResponse("""
            "videoDetails":{"videoId":"Fixture123_","title":"HDR fixture","lengthSeconds":"10"},
            "streamingData":{"adaptiveFormats":[{
              "itag":337,
              "url":"https://fixture.googlevideo.com/videoplayback?id=hdr&itag=337",
              "mimeType":"video/webm; codecs=\"vp9.2\"",
              "width":3840,"height":2160,"fps":60,"bitrate":25000000,"contentLength":"100",
              "colorInfo":{"primaries":"COLOR_PRIMARIES_BT2020"}
            }]}
            """));

        Assert.True(result.IsSuccess, result.Error?.Message);
        Assert.True(result.Value.Metadata.Formats.Single().IsHdr);
    }

    private static string PlayerResponse(string body) => $$"""
        <script>var ytInitialPlayerResponse={
          "playabilityStatus":{"status":"OK"},
          {{body}}
        };</script>
        """;
}
